spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 30s

jwt:
  secret-key: ${JWT_SECRET_KEY:test123456}
  access-exp: ${JWT_ACCESS_EXP:12345}
  refresh-exp: ${JWT_REFRESH_EXP:1234567}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
